GET http://localhost:3310/ads

###

POST http://localhost:3310/ads
Content-Type: application/json

{
    "title": "Bike to sell",
    "description":
      "My bike is blue, working fine. I'm selling it because I've got a new one",
    "owner": "bike.seller@gmail.com",
    "price": 100,
    "picture":
      "https://images.lecho.be/view?iid=dc:113129565&context=ONLINE&ratio=16/9&width=640&u=1508242455000",
    "location": "Paris",
    "createdAt": "2023-09-05T10:13:14.755Z"
  }

###

PUT http://localhost:3310/ads/11
Content-Type: application/json

{
  "owner": "Pablo",
  "title": "Bulshit",
  "price": 145,
  "createdAt": "2000-10-11"
}

###

PATCH http://localhost:3310/ads/11
Content-Type: application/json

{
  "owner": "Max",
  "title": "Beer",
  "price": 100,
  "createdAt": "2000-10-10"
}

###

DELETE http://localhost:3310/ads/52