@baseUrl = http://localhost:3310/category
@adId = 4

### GET all category
GET {{baseUrl}}

###

### POST a new ad
POST {{baseUrl}}

###

### PUT to update an ad
PUT {{baseUrl}}/{{adId}}

###

### PATCH to modify an ad
PATCH {{baseUrl}}/{{adId}}

###

### DELETE an ad
DELETE {{baseUrl}}/{{adId}}